//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee.DigitalPlatform.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FilterBuilderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilterBuilderResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coffee.DigitalPlatform.Controls.Properties.FilterBuilderResource", typeof(FilterBuilderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add expression 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_AddExpression {
            get {
                return ResourceManager.GetString("FilterBuilder_AddExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add group 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_AddGroup {
            get {
                return ResourceManager.GetString("FilterBuilder_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_And {
            get {
                return ResourceManager.GetString("FilterBuilder_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure? 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_AreYouSure {
            get {
                return ResourceManager.GetString("FilterBuilder_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contains 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Contains {
            get {
                return ResourceManager.GetString("FilterBuilder_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete item 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_DeleteItem {
            get {
                return ResourceManager.GetString("FilterBuilder_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filter has unsaved changes. Are you sure you want to close the editor without saving changes? 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_DiscardChanges {
            get {
                return ResourceManager.GetString("FilterBuilder_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 does not contain 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_DoesNotContain {
            get {
                return ResourceManager.GetString("FilterBuilder_DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 does not end with 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_DoesNotEndWith {
            get {
                return ResourceManager.GetString("FilterBuilder_DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 does not match 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_DoesNotMatch {
            get {
                return ResourceManager.GetString("FilterBuilder_DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 does not start with 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_DoesNotStartWith {
            get {
                return ResourceManager.GetString("FilterBuilder_DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ends with 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_EndsWith {
            get {
                return ResourceManager.GetString("FilterBuilder_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is equal to 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_EqualTo {
            get {
                return ResourceManager.GetString("FilterBuilder_EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Exception_Message_ConditionIsNotSupported_Pattern {
            get {
                return ResourceManager.GetString("FilterBuilder_Exception_Message_ConditionIsNotSupported_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter {0} is not supported. 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Exception_Message_ParameterIsNotSupported_Pattern {
            get {
                return ResourceManager.GetString("FilterBuilder_Exception_Message_ParameterIsNotSupported_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Exception_Message_TypeIsNotSupported_Pattern {
            get {
                return ResourceManager.GetString("FilterBuilder_Exception_Message_TypeIsNotSupported_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field is required 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_FieldIsRequired {
            get {
                return ResourceManager.GetString("FilterBuilder_FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 broken 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_FilterBuilderControl_TextBlock_Text_Broken {
            get {
                return ResourceManager.GetString("FilterBuilder_FilterBuilderControl_TextBlock_Text_Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0} items of {1}&quot; 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_FilteredItemsOfPattern {
            get {
                return ResourceManager.GetString("FilterBuilder_FilteredItemsOfPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is greater than 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_GreaterThan {
            get {
                return ResourceManager.GetString("FilterBuilder_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is greater than or equal to 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterBuilder_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Hide {
            get {
                return ResourceManager.GetString("FilterBuilder_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is empty 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_IsEmpty {
            get {
                return ResourceManager.GetString("FilterBuilder_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is null 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_IsNull {
            get {
                return ResourceManager.GetString("FilterBuilder_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is less than 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_LessThan {
            get {
                return ResourceManager.GetString("FilterBuilder_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is less than 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_LessThan1 {
            get {
                return ResourceManager.GetString("FilterBuilder_LessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is less than or equal to 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterBuilder_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live preview 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_LivePreview {
            get {
                return ResourceManager.GetString("FilterBuilder_LivePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live update 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_LiveUpdate {
            get {
                return ResourceManager.GetString("FilterBuilder_LiveUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 matches 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Matches {
            get {
                return ResourceManager.GetString("FilterBuilder_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Name {
            get {
                return ResourceManager.GetString("FilterBuilder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is not equal to 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_NotEqualTo {
            get {
                return ResourceManager.GetString("FilterBuilder_NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not filtered 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_NotFiltered {
            get {
                return ResourceManager.GetString("FilterBuilder_NotFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is not empty 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_NotIsEmpty {
            get {
                return ResourceManager.GetString("FilterBuilder_NotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is not null 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_NotIsNull {
            get {
                return ResourceManager.GetString("FilterBuilder_NotIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Or {
            get {
                return ResourceManager.GetString("FilterBuilder_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filter has some invalid expressions which will be ignored while filtering. Are you sure you want to save this filter? 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_SaveBroken {
            get {
                return ResourceManager.GetString("FilterBuilder_SaveBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_Show {
            get {
                return ResourceManager.GetString("FilterBuilder_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete filter? 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_ShowAsync_DeleteFilterQuestion_Caption {
            get {
                return ResourceManager.GetString("FilterBuilder_ShowAsync_DeleteFilterQuestion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete filter &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_ShowAsync_Message_AreYouSureYouWantToDeleteFilterQuestion_Pattern {
            get {
                return ResourceManager.GetString("FilterBuilder_ShowAsync_Message_AreYouSureYouWantToDeleteFilterQuestion_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 starts with 的本地化字符串。
        /// </summary>
        internal static string FilterBuilder_StartsWith {
            get {
                return ResourceManager.GetString("FilterBuilder_StartsWith", resourceCulture);
            }
        }
    }
}
